export const palabrasProhibidas = [
    'cabrón',
    'puta',
    'joder',
    'mierda',
    'coño',
    'carajo',
    'gilipollas',
    'hostia',
    'hijo de puta',
    'pendejo',
    'chingada',
    'mamón',
    'culero',
    'chupapollas',
    'maricón',
    'puto',
    'pelotudo',
    'picha',
    'polla',
    'verga',
    'culo',
    'bastardo',
    'idiota',
    'estúpido',
    'me cago en',
    'tonto del culo',
    'imbécil',
    'capullo',
  ];