export const poblacionesEspana = [
    'Adra',
    'Aguilar de Campoo',
    'Albacete',
    'Alcalá de Guadaíra',
    'Alcalá de Henares',
    'Alcázar de San Juan',
    'Alcobendas',
    'Alcorcón',
    'Alcoy',
    'Alegría-Dulantzi',
    'Alfaro',
    'Algeciras',
    'Algemesí',
    'Alhaurín de la Torre',
    'Alhaurín el Grande',
    'Alicante',
    'Aljaraque',
    'Almansa',
    'Almazán',
    'Almería',
    'Almonte',
    'Almoradí',
    'Andorra',
    'Andújar',
    'Antequera',
    'Aranda de Duero',
    'Aranjuez',
    'Arenas de San Pedro',
    'Arnedo',
    'Arrasate-Mondragón',
    'Arrecife',
    'Arroyomolinos',
    'Astorga',
    'Ávila',
    'Ayamonte',
    'Ayora',
    'Badajoz',
    'Badalona',
    'Bailén',
    'Balaguer',
    'Balmaseda',
    'Bañeres',
    'Barakaldo',
    'Barbate',
    'Barcelona',
    'Baza',
    'Benalmádena',
    'Benavente',
    'Benicarló',
    'Benidorm',
    'Benifaió',
    'Benissa',
    'Bergara',
    'Betanzos',
    'Bilbao',
    'Blanes',
    'Boadilla del Monte',
    'Borriana',
    'Burgos',
    'Cáceres',
    'Cadalso de los Vidrios',
    'Cádiz',
    'Calafell',
    'Calahorra',
    'Calamocha',
    'Calatayud',
    'Calvià',
    'Cangas',
    'Cangas de Onís',
    'Cañete',
    'Carballiño',
    'Carcaixent',
    'Carlet',
    'Carmona',
    'Cartagena',
    'Caspe',
    'Castellón',
    'Castril',
    'Cazorla',
    'Ceuta',
    'Cieza',
    'Ciudad Real',
    'Córdoba',
    'Cornellà de Llobregat',
    'Coslada',
    'Cuenca',
    'Cullera',
    'Daimiel',
    'Denia',
    'Dos Hermanas',
    'Durango',
    'Écija',
    'El Ejido',
    'El Vendrell',
    'Elche',
    'Elda',
    'Elgoibar',
    'Ejea de los Caballeros',
    'Esparreguera',
    'Estella-Lizarra',
    'Estepona',
    'Figueres',
    'Fuenlabrada',
    'Gandía',
    'Gavà',
    'Gijón',
    'Girona',
    'Gorliz',
    'Granada',
    'Granollers',
    'Getafe',
    'Getxo',
    'Güímar',
    'Guadalajara',
    'Güeñes',
    'Hellín',
    'Hernani',
    'Hondarribia',
    'Huesca',
    'Ibiza',
    'Illescas',
    'Inca',
    'Ingenio',
    'Irún',
    'Jaca',
    'Jaén',
    'Jerez de la Frontera',
    'Jumilla',
    'La Bañeza',
    'La Línea de la Concepción',
    'La Orotava',
    'La Roda',
    'La Unión',
    'La Vall d’Uixó',
    'Laguna de Duero',
    'Langreo',
    'Laredo',
    'Las Palmas',
    'León',
    'Linares',
    'Lleida',
    'Logroño',
    'Lorca',
    'Lugo',
    'Manacor',
    'Manises',
    'Manresa',
    'Mataró',
    'Medina del Campo',
    'Melilla',
    'Mérida',
    'Miranda de Ebro',
    'Mislata',
    'Molina de Segura',
    'Mollet del Vallès',
    'Moncada',
    'Monzón',
    'Móstoles',
    'Motril',
    'Mula',
    'Munguía',
    'Murcia',
    'Navalmoral de la Mata',
    'Navarro',
    'Nerja',
    'Níjar',
    'Noia',
    'Novelda',
    'Ocaña',
    'Olot',
    'Ondarroa',
    'Ontinyent',
    'Orense',
    'Orihuela',
    'Ourense',
    'Oviedo',
    'Palencia',
    'Palma de Mallorca',
    'Paterna',
    'Pinto',
    'Pola de Siero',
    'Ponferrada',
    'Pontevedra',
    'Portugalete',
    'Puertollano',
    'Rincón de la Victoria',
    'Rivas-Vaciamadrid',
    'Ronda',
    'Sabadell',
    'Sagunto',
    'Salamanca',
    'Salou',
    'San Fernando',
    'San Javier',
    'San Sebastián',
    'Santa Coloma de Gramenet',
    'Santa Cruz de Tenerife',
    'Santa Eulària des Riu',
    'Santander',
    'Santiago de Compostela',
    'Segovia',
    'Sevilla',
    'Siero',
    'Sitges',
    'Soria',
    'Talavera de la Reina',
    'Tarragona',
    'Tarazona',
    'Telde',
    'Terrassa',
    'Toledo',
    'Torrevieja',
    'Tres Cantos',
    'Utrera',
    'Valdemoro',
    'Valdepeñas',
    'Valencia',
    'Valladolid',
    'Vélez-Málaga',
    'Vendrell',
    'Vigo',
    'Vilanova i la Geltrú',
    'Villajoyosa',
    'Villena',
    'Vinaròs',
    'Vitoria-Gasteiz',
    'Yecla',
    'Zamora',
    'Zaragoza',
    'Zarautz'
  ];
  